### ISSUE TITLE
slight improvement ideas

### ISSUE THREAD

**Issue by dvolgyes** [aziezahmed/newsapi-cli#1]
Hi,

First of all, it is a a great and clean project! Thank you for it.

However, I have some suggestions for improving it.

First, the API key could be detected from environmental variable, e.g. 
```NEWSAPI_KEY = os.environ.get("NEWSAPI_KEY", __api_key__)```
and only rely on the built-in one, if necessary.

Secondly, besides the sources, headlines to specific countries could be shown, e.g
news uk   or news au.

Finally, country codes could handle categories, e.g. with slash notation:
news uk/business

The logic could be simply: if the source is not a specific publisher, then assume it as a country.
If it has a slash (/), then the first part is the country code, the second is the category.

(Besides "news sources", there could be a "news countries" and a "news categories" part in the help.)

Finally, as far as I seen, there is a mismatch between pypi and the github repository,
so maybe it would be nice to release a new pypi package. 
(Interestingly, the pypi package has higher version number than the github code, however, the github code has fresher code. Maybe it would be wise to bump the versions to the same level.)

**Comment by aziezahmed** [comment]
hi @dvolgyes,
Thanks for the suggestions. I have added the code for the countries and categories as you have suggested. 
I'll be looking at the api key next.
After that I'll probably release a new version with both these changes.

**Comment by dvolgyes** [comment]
Thanks a lot!
